version: '3'

services:
    media-manager:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        container_name: media-manager
        volumes:
            - "${DIR}/uploads:${UPLOADS_DIR}"
        env_file:
          - ".env"
        environment:
            - NODE_ENV=production
            - MONGO_URL=mongodb://mongodb/media-manager
            - ACCOUNT_NAME
            - ACCOUNT_PASSWORD
            - DEMO
            - EXPOSED_PORT
        networks:
            - webappnetwork
        depends_on:
            - mongodb
        ports:
            - "${EXPOSED_PORT}:${PORT}"
    mongodb:
        image: mongo
        restart: always
        container_name: mongodb
        volumes:
            - '${DIR}/db:/data/db'
        command: mongod --noauth --smallfiles
        networks:
            - webappnetwork
networks:
    webappnetwork:
        driver: bridge
